# Data Filtering

In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel(r"D:\UV DA\UV python\Sales_Project_Data.xlsx")

In [5]:
df

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,East,Mobile,Electronics,990,5,160.68,2025-04-10
1,2,North,Laptop,Electronics,1413,4,381.51,2025-03-25
2,3,West,Laptop,Electronics,1519,2,341.82,2025-03-19
3,4,North,Headphones,Accessories,1689,4,476.28,2025-05-14
4,5,East,Laptop,Electronics,790,1,88.48,2025-04-02
...,...,...,...,...,...,...,...,...
195,196,South,Tablet,Electronics,290,5,83.13,2025-04-24
196,197,West,Headphones,Accessories,303,4,75.10,2025-01-01
197,198,North,Mobile,Electronics,1591,2,358.29,2025-03-04
198,199,South,Monitor,Electronics,1817,1,390.65,2025-06-27
199,200,East,Mobile,Electronics,1061,5,207.12,2025-02-27

In [6]:
df[df['Sales'] > 1000]

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
1,2,North,Laptop,Electronics,1413,4,381.51,2025-03-25
2,3,West,Laptop,Electronics,1519,2,341.82,2025-03-19
3,4,North,Headphones,Accessories,1689,4,476.28,2025-05-14
7,8,North,Laptop,Electronics,1665,5,465.41,2025-04-10
9,10,West,Laptop,Electronics,1307,3,348.16,2025-06-30
...,...,...,...,...,...,...,...,...
192,193,West,Tablet,Electronics,1545,3,200.46,2025-01-03
193,194,South,Monitor,Electronics,1314,4,283.61,2025-02-13
197,198,North,Mobile,Electronics,1591,2,358.29,2025-03-04
198,199,South,Monitor,Electronics,1817,1,390.65,2025-06-27
199,200,East,Mobile,Electronics,1061,5,207.12,2025-02-27

In [7]:
df[df['Profit'] < 200]

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,East,Mobile,Electronics,990,5,160.68,2025-04-10
4,5,East,Laptop,Electronics,790,1,88.48,2025-04-02
5,6,North,Tablet,Electronics,528,1,57.72,2025-01-17
6,7,South,Tablet,Electronics,790,5,136.22,2025-03-31
8,9,East,Headphones,Accessories,683,4,93.44,2025-05-08
...,...,...,...,...,...,...,...,...
188,189,South,Mobile,Electronics,608,4,82.00,2025-03-06
191,192,South,Headphones,Accessories,1203,5,135.33,2025-01-04
194,195,South,Headphones,Accessories,986,1,138.77,2025-04-11
195,196,South,Tablet,Electronics,290,5,83.13,2025-04-24
196,197,West,Headphones,Accessories,303,4,75.10,2025-01-01

In [8]:
df[df['Region'] == 'East']

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,East,Mobile,Electronics,990,5,160.68,2025-04-10
4,5,East,Laptop,Electronics,790,1,88.48,2025-04-02
8,9,East,Headphones,Accessories,683,4,93.44,2025-05-08
10,11,East,Laptop,Electronics,219,2,64.57,2025-05-20
13,14,East,Mobile,Electronics,1520,1,410.45,2025-01-22
15,16,East,Monitor,Electronics,1337,3,329.36,2025-06-08
21,22,East,Monitor,Electronics,666,3,144.40,2025-05-15
24,25,East,Mobile,Electronics,1732,3,192.49,2025-02-18
29,30,East,Laptop,Electronics,1062,5,226.91,2025-05-07
31,32,East,Headphones,Accessories,1204,5,234.83,2025-02-06
43,44,East,Tablet,Electronics,1058,3,225.63,2025-04-01
47,48,East,Monitor,Electronics,814,3,211.56,2025-05-19
52,53,East,Tablet,Electronics,1146,2,126.65,2025-01-08
56,57,East,Mobile,Electronics,658,3,132.62,2025-02-08
59,60,East,Monitor,Electronics,632,5,120.57,2025-05-31
61,62,East,Laptop,Electronics,1718,5,230.88,2025-06-14
63,64,East,Laptop,Electronics,538,1,160.17,2025-06-22
68,69,East,Tablet,Electronics,1675,4,285.07,2025-04-06
71,72,East,Laptop,Electronics,1184,1,317.92,2025-05-03
73,74,East,Laptop,Electronics,1638,5,250.07,2025-03-15
76,77,East,Tablet,Electronics,465,1,116.66,2025-06-08
79,80,East,Headphones,Accessories,1433,1,320.05,2025-02-01
84,85,East,Laptop,Electronics,420,2,87.25,2025-06-11
89,90,East,Mobile,Electronics,1612,1,166.90,2025-04-07
99,100,East,Tablet,Electronics,1855,3,228.81,2025-04-14
101,102,East,Monitor,Electronics,1518,2,371.20,2025-05-09
112,113,East,Monitor,Electronics,1823,5,424.40,2025-01-01
114,115,East,Laptop,Electronics,731,2,133.65,2025-03-06
121,122,East,Tablet,Electronics,1761,2,413.44,2025-05-12
123,124,East,Headphones,Accessories,1404,4,311.98,2025-03-20
124,125,East,Headphones,Accessories,1686,3,381.46,2025-06-30
127,128,East,Headphones,Accessories,1987,5,292.27,2025-05-25
133,134,East,Laptop,Electronics,320,3,76.77,2025-03-28
135,136,East,Monitor,Electronics,602,3,65.76,2025-05-05
137,138,East,Monitor,Electronics,1684,4,313.23,2025-01-17
141,142,East,Monitor,Electronics,1124,3,208.24,2025-02-05
143,144,East,Monitor,Electronics,385,3,48.25,2025-05-18
148,149,East,Tablet,Electronics,990,4,165.59,2025-03-31
155,156,East,Monitor,Electronics,1734,1,443.32,2025-02-27
163,164,East,Monitor,Electronics,1659,3,397.74,2025-06-07
165,166,East,Monitor,Electronics,1620,2,365.07,2025-04-20
167,168,East,Tablet,Electronics,842,1,207.08,2025-06-25
170,171,East,Laptop,Electronics,1531,3,450.83,2025-02-13
172,173,East,Mobile,Electronics,1282,2,357.31,2025-04-20
180,181,East,Mobile,Electronics,801,1,155.42,2025-02-15
185,186,East,Laptop,Electronics,1261,5,272.60,2025-06-06
186,187,East,Laptop,Electronics,1166,4,140.12,2025-01-20
187,188,East,Mobile,Electronics,1126,1,283.32,2025-01-14
199,200,East,Mobile,Electronics,1061,5,207.12,2025-02-27

In [9]:
df[(df['Sales'] > 1000) & (df['Profit'] > 200)]

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
1,2,North,Laptop,Electronics,1413,4,381.51,2025-03-25
2,3,West,Laptop,Electronics,1519,2,341.82,2025-03-19
3,4,North,Headphones,Accessories,1689,4,476.28,2025-05-14
7,8,North,Laptop,Electronics,1665,5,465.41,2025-04-10
9,10,West,Laptop,Electronics,1307,3,348.16,2025-06-30
...,...,...,...,...,...,...,...,...
192,193,West,Tablet,Electronics,1545,3,200.46,2025-01-03
193,194,South,Monitor,Electronics,1314,4,283.61,2025-02-13
197,198,North,Mobile,Electronics,1591,2,358.29,2025-03-04
198,199,South,Monitor,Electronics,1817,1,390.65,2025-06-27
199,200,East,Mobile,Electronics,1061,5,207.12,2025-02-27

In [10]:
df[(df['Region'] == 'East') & (df['Category'] == 'Electronics')]

     Order_ID Region  Product     Category  Sales  Quantity  Profit       Date
0           1   East   Mobile  Electronics    990         5  160.68 2025-04-10
4           5   East   Laptop  Electronics    790         1   88.48 2025-04-02
10         11   East   Laptop  Electronics    219         2   64.57 2025-05-20
13         14   East   Mobile  Electronics   1520         1  410.45 2025-01-22
15         16   East  Monitor  Electronics   1337         3  329.36 2025-06-08
21         22   East  Monitor  Electronics    666         3  144.40 2025-05-15
24         25   East   Mobile  Electronics   1732         3  192.49 2025-02-18
29         30   East   Laptop  Electronics   1062         5  226.91 2025-05-07
43         44   East   Tablet  Electronics   1058         3  225.63 2025-04-01
47         48   East  Monitor  Electronics    814         3  211.56 2025-05-19
52         53   East   Tablet  Electronics   1146         2  126.65 2025-01-08
56         57   East   Mobile  Electronics    658         3  132.62 2025-02-08
59         60   East  Monitor  Electronics    632         5  120.57 2025-05-31
61         62   East   Laptop  Electronics   1718         5  230.88 2025-06-14
63         64   East   Laptop  Electronics    538         1  160.17 2025-06-22
68         69   East   Tablet  Electronics   1675         4  285.07 2025-04-06
71         72   East   Laptop  Electronics   1184         1  317.92 2025-05-03
73         74   East   Laptop  Electronics   1638         5  250.07 2025-03-15
76         77   East   Tablet  Electronics    465         1  116.66 2025-06-08
84         85   East   Laptop  Electronics    420         2   87.25 2025-06-11
89         90   East   Mobile  Electronics   1612         1  166.90 2025-04-07
99        100   East   Tablet  Electronics   1855         3  228.81 2025-04-14
101       102   East  Monitor  Electronics   1518         2  371.20 2025-05-09
112       113   East  Monitor  Electronics   1823         5  424.40 2025-01-01
114       115   East   Laptop  Electronics    731         2  133.65 2025-03-06
121       122   East   Tablet  Electronics   1761         2  413.44 2025-05-12
133       134   East   Laptop  Electronics    320         3   76.77 2025-03-28
135       136   East  Monitor  Electronics    602         3   65.76 2025-05-05
137       138   East  Monitor  Electronics   1684         4  313.23 2025-01-17
141       142   East  Monitor  Electronics   1124         3  208.24 2025-02-05
143       144   East  Monitor  Electronics    385         3   48.25 2025-05-18
148       149   East   Tablet  Electronics    990         4  165.59 2025-03-31
155       156   East  Monitor  Electronics   1734         1  443.32 2025-02-27
163       164   East  Monitor  Electronics   1659         3  397.74 2025-06-07
165       166   East  Monitor  Electronics   1620         2  365.07 2025-04-20
167       168   East   Tablet  Electronics    842         1  207.08 2025-06-25
170       171   East   Laptop  Electronics   1531         3  450.83 2025-02-13
172       173   East   Mobile  Electronics   1282         2  357.31 2025-04-20
180       181   East   Mobile  Electronics    801         1  155.42 2025-02-15
185       186   East   Laptop  Electronics   1261         5  272.60 2025-06-06
186       187   East   Laptop  Electronics   1166         4  140.12 2025-01-20
187       188   East   Mobile  Electronics   1126         1  283.32 2025-01-14
199       200   East   Mobile  Electronics   1061         5  207.12 2025-02-27

In [11]:
df[df['Region'].isin(['East', 'West'])]

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,East,Mobile,Electronics,990,5,160.68,2025-04-10
2,3,West,Laptop,Electronics,1519,2,341.82,2025-03-19
4,5,East,Laptop,Electronics,790,1,88.48,2025-04-02
8,9,East,Headphones,Accessories,683,4,93.44,2025-05-08
9,10,West,Laptop,Electronics,1307,3,348.16,2025-06-30
...,...,...,...,...,...,...,...,...
187,188,East,Mobile,Electronics,1126,1,283.32,2025-01-14
189,190,West,Mobile,Electronics,1902,2,560.87,2025-02-19
192,193,West,Tablet,Electronics,1545,3,200.46,2025-01-03
196,197,West,Headphones,Accessories,303,4,75.10,2025-01-01
199,200,East,Mobile,Electronics,1061,5,207.12,2025-02-27

In [12]:
df[df['Category'].isin(['Furniture', 'Clothing'])]

Empty DataFrame
Columns: [Order_ID, Region, Product, Category, Sales, Quantity, Profit, Date]
Index: []

In [13]:
df[df['Product'].str.contains('Laptop')]

     Order_ID Region Product     Category  Sales  Quantity  Profit       Date
1           2  North  Laptop  Electronics   1413         4  381.51 2025-03-25
2           3   West  Laptop  Electronics   1519         2  341.82 2025-03-19
4           5   East  Laptop  Electronics    790         1   88.48 2025-04-02
7           8  North  Laptop  Electronics   1665         5  465.41 2025-04-10
9          10   West  Laptop  Electronics   1307         3  348.16 2025-06-30
10         11   East  Laptop  Electronics    219         2   64.57 2025-05-20
14         15  South  Laptop  Electronics    726         5  138.63 2025-04-24
25         26  South  Laptop  Electronics    928         5  122.06 2025-03-12
29         30   East  Laptop  Electronics   1062         5  226.91 2025-05-07
41         42  South  Laptop  Electronics    286         5   82.26 2025-05-26
44         45  North  Laptop  Electronics   1580         2  403.89 2025-06-21
51         52  South  Laptop  Electronics    374         3   98.10 2025-05-29
55         56  North  Laptop  Electronics    607         5   89.53 2025-01-15
61         62   East  Laptop  Electronics   1718         5  230.88 2025-06-14
63         64   East  Laptop  Electronics    538         1  160.17 2025-06-22
64         65  North  Laptop  Electronics   1916         2  541.97 2025-03-20
71         72   East  Laptop  Electronics   1184         1  317.92 2025-05-03
73         74   East  Laptop  Electronics   1638         5  250.07 2025-03-15
77         78   West  Laptop  Electronics    547         5  161.98 2025-01-27
84         85   East  Laptop  Electronics    420         2   87.25 2025-06-11
85         86   West  Laptop  Electronics    315         4   70.20 2025-04-16
91         92  South  Laptop  Electronics    348         1   81.34 2025-02-19
96         97  North  Laptop  Electronics   1413         5  218.79 2025-03-10
97         98  North  Laptop  Electronics   1220         3  358.11 2025-06-19
98         99  North  Laptop  Electronics    302         2   48.24 2025-02-12
102       103  North  Laptop  Electronics   1330         5  283.73 2025-04-02
104       105   West  Laptop  Electronics    640         1  133.72 2025-03-31
113       114  North  Laptop  Electronics    728         3  151.98 2025-05-06
114       115   East  Laptop  Electronics    731         2  133.65 2025-03-06
116       117  North  Laptop  Electronics    754         1  152.85 2025-03-26
117       118   West  Laptop  Electronics    854         5  197.31 2025-01-05
131       132  South  Laptop  Electronics   1799         2  399.69 2025-04-09
132       133  North  Laptop  Electronics   1784         5  308.10 2025-04-21
133       134   East  Laptop  Electronics    320         3   76.77 2025-03-28
149       150  South  Laptop  Electronics   1655         3  382.19 2025-04-07
150       151  South  Laptop  Electronics   1524         2  379.09 2025-06-01
154       155   West  Laptop  Electronics    468         5  117.57 2025-01-27
156       157   West  Laptop  Electronics   1716         5  230.86 2025-02-24
157       158  South  Laptop  Electronics    695         3  104.73 2025-01-23
161       162   West  Laptop  Electronics    927         5  201.36 2025-01-14
170       171   East  Laptop  Electronics   1531         3  450.83 2025-02-13
176       177   West  Laptop  Electronics    302         2   65.18 2025-06-11
183       184  South  Laptop  Electronics   1877         4  436.83 2025-05-24
185       186   East  Laptop  Electronics   1261         5  272.60 2025-06-06
186       187   East  Laptop  Electronics   1166         4  140.12 2025-01-20

In [14]:
df[df['Region'].str.startswith('N')]

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
1,2,North,Laptop,Electronics,1413,4,381.51,2025-03-25
3,4,North,Headphones,Accessories,1689,4,476.28,2025-05-14
5,6,North,Tablet,Electronics,528,1,57.72,2025-01-17
7,8,North,Laptop,Electronics,1665,5,465.41,2025-04-10
11,12,North,Mobile,Electronics,1897,2,429.76,2025-01-31
12,13,North,Mobile,Electronics,1755,5,501.15,2025-01-07
17,18,North,Tablet,Electronics,733,4,140.76,2025-02-26
23,24,North,Monitor,Electronics,1930,4,241.03,2025-02-17
34,35,North,Monitor,Electronics,944,1,154.84,2025-05-08
44,45,North,Laptop,Electronics,1580,2,403.89,2025-06-21
46,47,North,Headphones,Accessories,567,2,143.64,2025-03-23
49,50,North,Tablet,Electronics,990,2,171.58,2025-02-02
53,54,North,Headphones,Accessories,1487,3,348.26,2025-02-13
55,56,North,Laptop,Electronics,607,5,89.53,2025-01-15
57,58,North,Headphones,Accessories,1828,1,295.80,2025-03-10
64,65,North,Laptop,Electronics,1916,2,541.97,2025-03-20
66,67,North,Mobile,Electronics,1067,1,235.80,2025-01-30
72,73,North,Headphones,Accessories,1812,3,542.04,2025-04-21
74,75,North,Mobile,Electronics,513,4,94.31,2025-05-27
80,81,North,Mobile,Electronics,635,5,73.91,2025-01-12
86,87,North,Headphones,Accessories,1147,5,247.37,2025-01-24
93,94,North,Headphones,Accessories,1739,2,248.14,2025-06-26
96,97,North,Laptop,Electronics,1413,5,218.79,2025-03-10
97,98,North,Laptop,Electronics,1220,3,358.11,2025-06-19
98,99,North,Laptop,Electronics,302,2,48.24,2025-02-12
102,103,North,Laptop,Electronics,1330,5,283.73,2025-04-02
103,104,North,Tablet,Electronics,1202,2,245.07,2025-02-21
106,107,North,Tablet,Electronics,929,5,264.97,2025-02-15
108,109,North,Tablet,Electronics,1613,5,223.46,2025-03-03
110,111,North,Monitor,Electronics,1996,2,512.83,2025-05-30
113,114,North,Laptop,Electronics,728,3,151.98,2025-05-06
116,117,North,Laptop,Electronics,754,1,152.85,2025-03-26
119,120,North,Mobile,Electronics,1290,1,339.52,2025-06-28
126,127,North,Tablet,Electronics,1443,2,301.03,2025-05-07
132,133,North,Laptop,Electronics,1784,5,308.10,2025-04-21
138,139,North,Monitor,Electronics,1208,4,341.97,2025-01-04
139,140,North,Monitor,Electronics,1503,1,367.35,2025-05-05
142,143,North,Monitor,Electronics,761,3,144.49,2025-02-01
145,146,North,Tablet,Electronics,674,3,112.30,2025-03-03
147,148,North,Headphones,Accessories,1146,3,332.22,2025-01-15
158,159,North,Monitor,Electronics,967,2,241.09,2025-06-02
162,163,North,Monitor,Electronics,232,4,39.90,2025-04-12
164,165,North,Mobile,Electronics,1467,5,431.75,2025-05-10
166,167,North,Monitor,Electronics,1943,4,540.90,2025-04-24
168,169,North,Monitor,Electronics,1674,3,205.99,2025-01-12
169,170,North,Monitor,Electronics,216,3,36.71,2025-06-10
174,175,North,Mobile,Electronics,1210,2,311.14,2025-03-13
175,176,North,Tablet,Electronics,404,1,115.07,2025-05-31
177,178,North,Headphones,Accessories,441,1,106.25,2025-02-07
181,182,North,Monitor,Electronics,443,4,69.07,2025-01-22
197,198,North,Mobile,Electronics,1591,2,358.29,2025-03-04

In [15]:
df['Date'] = pd.to_datetime(df['Date'])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  200 non-null    int64
 1   Region    200 non-null    object
 2   Product   200 non-null    object
 3   Category  200 non-null    object
 4   Sales     200 non-null    int64
 5   Quantity  200 non-null    int64
 6   Profit    200 non-null    float64
 7   Date      200 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), object(3)
memory usage: 12.6+ KB

In [18]:
df[df['Date'].dt.month == 1]

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
5,6,North,Tablet,Electronics,528,1,57.72,2025-01-17
11,12,North,Mobile,Electronics,1897,2,429.76,2025-01-31
12,13,North,Mobile,Electronics,1755,5,501.15,2025-01-07
13,14,East,Mobile,Electronics,1520,1,410.45,2025-01-22
48,49,West,Monitor,Electronics,900,4,132.23,2025-01-01
52,53,East,Tablet,Electronics,1146,2,126.65,2025-01-08
55,56,North,Laptop,Electronics,607,5,89.53,2025-01-15
66,67,North,Mobile,Electronics,1067,1,235.80,2025-01-30
77,78,West,Laptop,Electronics,547,5,161.98,2025-01-27
80,81,North,Mobile,Electronics,635,5,73.91,2025-01-12
81,82,South,Headphones,Accessories,1031,5,171.53,2025-01-15
86,87,North,Headphones,Accessories,1147,5,247.37,2025-01-24
112,113,East,Monitor,Electronics,1823,5,424.40,2025-01-01
117,118,West,Laptop,Electronics,854,5,197.31,2025-01-05
137,138,East,Monitor,Electronics,1684,4,313.23,2025-01-17
138,139,North,Monitor,Electronics,1208,4,341.97,2025-01-04
147,148,North,Headphones,Accessories,1146,3,332.22,2025-01-15
154,155,West,Laptop,Electronics,468,5,117.57,2025-01-27
157,158,South,Laptop,Electronics,695,3,104.73,2025-01-23
160,161,West,Mobile,Electronics,1223,4,167.68,2025-01-15
161,162,West,Laptop,Electronics,927,5,201.36,2025-01-14
168,169,North,Monitor,Electronics,1674,3,205.99,2025-01-12
181,182,North,Monitor,Electronics,443,4,69.07,2025-01-22
186,187,East,Laptop,Electronics,1166,4,140.12,2025-01-20
187,188,East,Mobile,Electronics,1126,1,283.32,2025-01-14
191,192,South,Headphones,Accessories,1203,5,135.33,2025-01-04
192,193,West,Tablet,Electronics,1545,3,200.46,2025-01-03
196,197,West,Headphones,Accessories,303,4,75.10,2025-01-01

In [19]:
df.nlargest(5, 'Sales')

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
110,111,North,Monitor,Electronics,1996,2,512.83,2025-05-30
127,128,East,Headphones,Accessories,1987,5,292.27,2025-05-25
35,36,West,Tablet,Electronics,1982,5,277.58,2025-05-14
69,70,West,Mobile,Electronics,1977,4,503.25,2025-04-05
166,167,North,Monitor,Electronics,1943,4,540.90,2025-04-24

In [20]:
df.nsmallest(5, 'Profit')

     Order_ID Region  Product     Category  Sales  Quantity  Profit       Date
169       170  North  Monitor  Electronics    216         3   36.71 2025-06-10
162       163  North  Monitor  Electronics    232         4   39.90 2025-04-12
98         99  North   Laptop  Electronics    302         2   48.24 2025-02-12
143       144   East  Monitor  Electronics    385         3   48.25 2025-05-18
50         51   West   Mobile  Electronics    482         3   50.16 2025-05-23

In [22]:
df['Profit_Percentage'] = (df['Profit'] / df['Sales']) * 100

In [23]:
df[df['Profit_Percentage'] > 20]

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date,Profit_Percentage
1,2,North,Laptop,Electronics,1413,4,381.51,2025-03-25,27.000000
2,3,West,Laptop,Electronics,1519,2,341.82,2025-03-19,22.502962
3,4,North,Headphones,Accessories,1689,4,476.28,2025-05-14,28.198934
7,8,North,Laptop,Electronics,1665,5,465.41,2025-04-10,27.952553
9,10,West,Laptop,Electronics,1307,3,348.16,2025-06-30,26.638103
...,...,...,...,...,...,...,...,...,...
193,194,South,Monitor,Electronics,1314,4,283.61,2025-02-13,21.583714
195,196,South,Tablet,Electronics,290,5,83.13,2025-04-24,28.665517
196,197,West,Headphones,Accessories,303,4,75.10,2025-01-01,24.785479
197,198,North,Mobile,Electronics,1591,2,358.29,2025-03-04,22.519799
198,199,South,Monitor,Electronics,1817,1,390.65,2025-06-27,21.499725

In [24]:
df.groupby('Region').agg({
    'Sales': 'sum',
    'Profit': 'sum',
    'Quantity': 'mean'
})

        Sales    Profit  Quantity
Region
East    57147  11412.59  2.918367
North   60326  13447.87  3.000000
South   50420   9270.28  3.521739
West    54294  11430.68  3.074074

In [25]:
df.groupby('Product')['Sales'].sum().sort_values(ascending=False).head(3)

Product
Mobile    48697
Laptop    46097
Tablet    42524
Name: Sales, dtype: int64

In [26]:
pd.pivot_table(df,
               values='Sales',
               index='Region',
               columns='Category',
               aggfunc='sum',
               fill_value=0)

Category  Accessories  Electronics
Region
East             8397        48750
North           11856        48470
South           15031        35389
West             7211        47083

In [27]:
df.loc[df.groupby('Region')['Sales'].idxmax()]

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date,Profit_Percentage
127,128,East,Headphones,Accessories,1987,5,292.27,2025-05-25,14.709109
110,111,North,Monitor,Electronics,1996,2,512.83,2025-05-30,25.692886
183,184,South,Laptop,Electronics,1877,4,436.83,2025-05-24,23.272776
35,36,West,Tablet,Electronics,1982,5,277.58,2025-05-14,14.005045