In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_excel(r"D:\UV DA\UV python\Unclean_Sales_Project_Data.xlsx")

In [7]:
df

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,NaN,Headphones,Accessories,"1,200",three,,2025/02/15
1,2,NaN,Laptop,Electronics,,three,,NaN
2,3,NaN,NaN,ELECTRONICS,NaN,,NaN,
3,4,NaN,NaN,ELECTRONICS,NaN,three,,2025-03-06 00:00:00
4,5,East,Tablet,Electronics,1500$,NaN,NaN,
5,6,NaN,Monitor,electronics,NaN,NaN,-,2025/02/15
6,7,East,Tablet,NaN,,NaN,-,
7,8,North,NaN,Accessories,1500$,NaN,70.22,
8,9,West,NaN,Electronics,"1,200",,109.44,2025-02-05 00:00:00
9,10,South,NaN,ELECTRONICS,NaN,0,NaN,15-03-2025
10,11,NaN,Laptop,Electronics,"1,200",three,NaN,NaN
11,12,West,Headphones,ELECTRONICS,"1,200",NaN,,
12,13,North,Headphones,electronics,NaN,NaN,NaN,15-03-2025
13,14,NaN,Laptop,electronics,,,NaN,
14,15,West,Laptop,Accessories,1783,1,,15-03-2025
15,16,North,Tablet,electronics,,,NaN,2025-02-17 00:00:00
16,17,North,NaN,ELECTRONICS,"1,200",,-,2025/02/15
17,18,NaN,Tablet,Electronics,,three,NaN,2025/02/15
18,19,NaN,Headphones,Accessories,"1,200",NaN,NaN,15-03-2025
19,20,NaN,NaN,ELECTRONICS,,three,,NaN
20,21,North,Mobile,Accessories,1007,three,,NaN
21,22,West,NaN,Electronics,NaN,NaN,NaN,2025-02-02 00:00:00
22,23,South,Monitor,Electronics,1487,,NaN,2025-03-18 00:00:00
23,24,NaN,NaN,NaN,1500$,,NaN,2025-01-08 00:00:00
24,25,West,Mobile,ELECTRONICS,,,-,2025-01-15 00:00:00
25,26,West,Mobile,Electronics,382,0,,
26,27,NaN,Laptop,electronics,"1,200",0,,
27,28,East,Monitor,ELECTRONICS,"1,200",NaN,459.39,
28,29,North,Headphones,NaN,NaN,0,214.92,
29,30,West,Monitor,Accessories,821,1,109.77,2025-01-12 00:00:00
30,31,NaN,Tablet,Electronics,237,,NaN,
31,32,NaN,Headphones,ELECTRONICS,1771,0,-,2025/02/15
32,33,NaN,Laptop,NaN,1500$,0,NaN,2025-02-20 00:00:00
33,34,South,Headphones,ELECTRONICS,NaN,4,107.67,
34,35,East,NaN,Accessories,"1,200",0,,2025-03-09 00:00:00
35,36,NaN,Laptop,electronics,NaN,5,NaN,15-03-2025
36,37,NaN,Monitor,ELECTRONICS,NaN,,NaN,NaN
37,38,NaN,NaN,NaN,"1,200",NaN,,NaN
38,39,West,Mobile,electronics,NaN,NaN,NaN,
39,40,South,NaN,Electronics,NaN,0,184.47,NaN
40,41,North,Monitor,Accessories,1500$,4,-,15-03-2025
41,42,South,NaN,NaN,"1,200",three,NaN,15-03-2025
42,43,East,NaN,NaN,"1,200",NaN,NaN,
43,44,NaN,NaN,NaN,NaN,4,NaN,2025-01-13 00:00:00
44,45,North,Headphones,ELECTRONICS,1500$,0,289.57,2025-01-07 00:00:00
45,46,North,Laptop,electronics,1500$,NaN,NaN,2025-03-06 00:00:00
46,47,East,Laptop,ELECTRONICS,1500$,3,-,NaN
47,48,East,Monitor,electronics,"1,200",,-,
48,49,NaN,Headphones,ELECTRONICS,284,5,,2025/02/15
49,50,NaN,Tablet,electronics,,0,,NaN

In [39]:
df.isnull().sum()

Order_ID     0
Region      21
Product     15
Category     8
Sales        0
Quantity    13
Profit      21
Date         0
dtype: int64

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  50 non-null     int64
 1   Region    29 non-null     object
 2   Product   35 non-null     object
 3   Category  42 non-null     object
 4   Sales     50 non-null     int64
 5   Quantity  37 non-null     object
 6   Profit    29 non-null     object
 7   Date      50 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 3.3+ KB

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,NaN,Headphones,Accessories,"1,200",three,,2025/02/15
1,2,NaN,Laptop,Electronics,,three,,NaN
2,3,NaN,NaN,ELECTRONICS,NaN,,NaN,
3,4,NaN,NaN,ELECTRONICS,NaN,three,,2025-03-06 00:00:00
4,5,East,Tablet,Electronics,1500$,NaN,NaN,
5,6,NaN,Monitor,electronics,NaN,NaN,-,2025/02/15
6,7,East,Tablet,NaN,,NaN,-,
7,8,North,NaN,Accessories,1500$,NaN,70.22,
8,9,West,NaN,Electronics,"1,200",,109.44,2025-02-05 00:00:00
9,10,South,NaN,ELECTRONICS,NaN,0,NaN,15-03-2025
10,11,NaN,Laptop,Electronics,"1,200",three,NaN,NaN
11,12,West,Headphones,ELECTRONICS,"1,200",NaN,,
12,13,North,Headphones,electronics,NaN,NaN,NaN,15-03-2025
13,14,NaN,Laptop,electronics,,,NaN,
14,15,West,Laptop,Accessories,1783,1,,15-03-2025
15,16,North,Tablet,electronics,,,NaN,2025-02-17 00:00:00
16,17,North,NaN,ELECTRONICS,"1,200",,-,2025/02/15
17,18,NaN,Tablet,Electronics,,three,NaN,2025/02/15
18,19,NaN,Headphones,Accessories,"1,200",NaN,NaN,15-03-2025
19,20,NaN,NaN,ELECTRONICS,,three,,NaN
20,21,North,Mobile,Accessories,1007,three,,NaN
21,22,West,NaN,Electronics,NaN,NaN,NaN,2025-02-02 00:00:00
22,23,South,Monitor,Electronics,1487,,NaN,2025-03-18 00:00:00
23,24,NaN,NaN,NaN,1500$,,NaN,2025-01-08 00:00:00
24,25,West,Mobile,ELECTRONICS,,,-,2025-01-15 00:00:00
25,26,West,Mobile,Electronics,382,0,,
26,27,NaN,Laptop,electronics,"1,200",0,,
27,28,East,Monitor,ELECTRONICS,"1,200",NaN,459.39,
28,29,North,Headphones,NaN,NaN,0,214.92,
29,30,West,Monitor,Accessories,821,1,109.77,2025-01-12 00:00:00
30,31,NaN,Tablet,Electronics,237,,NaN,
31,32,NaN,Headphones,ELECTRONICS,1771,0,-,2025/02/15
32,33,NaN,Laptop,NaN,1500$,0,NaN,2025-02-20 00:00:00
33,34,South,Headphones,ELECTRONICS,NaN,4,107.67,
34,35,East,NaN,Accessories,"1,200",0,,2025-03-09 00:00:00
35,36,NaN,Laptop,electronics,NaN,5,NaN,15-03-2025
36,37,NaN,Monitor,ELECTRONICS,NaN,,NaN,NaN
37,38,NaN,NaN,NaN,"1,200",NaN,,NaN
38,39,West,Mobile,electronics,NaN,NaN,NaN,
39,40,South,NaN,Electronics,NaN,0,184.47,NaN
40,41,North,Monitor,Accessories,1500$,4,-,15-03-2025
41,42,South,NaN,NaN,"1,200",three,NaN,15-03-2025
42,43,East,NaN,NaN,"1,200",NaN,NaN,
43,44,NaN,NaN,NaN,NaN,4,NaN,2025-01-13 00:00:00
44,45,North,Headphones,ELECTRONICS,1500$,0,289.57,2025-01-07 00:00:00
45,46,North,Laptop,electronics,1500$,NaN,NaN,2025-03-06 00:00:00
46,47,East,Laptop,ELECTRONICS,1500$,3,-,NaN
47,48,East,Monitor,electronics,"1,200",,-,
48,49,NaN,Headphones,ELECTRONICS,284,5,,2025/02/15
49,50,NaN,Tablet,electronics,,0,,NaN

In [13]:
df.fillna("abc")

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,abc,Headphones,Accessories,"1,200",three,,2025/02/15
1,2,abc,Laptop,Electronics,,three,,abc
2,3,abc,abc,ELECTRONICS,abc,,abc,
3,4,abc,abc,ELECTRONICS,abc,three,,2025-03-06 00:00:00
4,5,East,Tablet,Electronics,1500$,abc,abc,
5,6,abc,Monitor,electronics,abc,abc,-,2025/02/15
6,7,East,Tablet,abc,,abc,-,
7,8,North,abc,Accessories,1500$,abc,70.22,
8,9,West,abc,Electronics,"1,200",,109.44,2025-02-05 00:00:00
9,10,South,abc,ELECTRONICS,abc,0,abc,15-03-2025
10,11,abc,Laptop,Electronics,"1,200",three,abc,abc
11,12,West,Headphones,ELECTRONICS,"1,200",abc,,
12,13,North,Headphones,electronics,abc,abc,abc,15-03-2025
13,14,abc,Laptop,electronics,,,abc,
14,15,West,Laptop,Accessories,1783,1,,15-03-2025
15,16,North,Tablet,electronics,,,abc,2025-02-17 00:00:00
16,17,North,abc,ELECTRONICS,"1,200",,-,2025/02/15
17,18,abc,Tablet,Electronics,,three,abc,2025/02/15
18,19,abc,Headphones,Accessories,"1,200",abc,abc,15-03-2025
19,20,abc,abc,ELECTRONICS,,three,,abc
20,21,North,Mobile,Accessories,1007,three,,abc
21,22,West,abc,Electronics,abc,abc,abc,2025-02-02 00:00:00
22,23,South,Monitor,Electronics,1487,,abc,2025-03-18 00:00:00
23,24,abc,abc,abc,1500$,,abc,2025-01-08 00:00:00
24,25,West,Mobile,ELECTRONICS,,,-,2025-01-15 00:00:00
25,26,West,Mobile,Electronics,382,0,,
26,27,abc,Laptop,electronics,"1,200",0,,
27,28,East,Monitor,ELECTRONICS,"1,200",abc,459.39,
28,29,North,Headphones,abc,abc,0,214.92,
29,30,West,Monitor,Accessories,821,1,109.77,2025-01-12 00:00:00
30,31,abc,Tablet,Electronics,237,,abc,
31,32,abc,Headphones,ELECTRONICS,1771,0,-,2025/02/15
32,33,abc,Laptop,abc,1500$,0,abc,2025-02-20 00:00:00
33,34,South,Headphones,ELECTRONICS,abc,4,107.67,
34,35,East,abc,Accessories,"1,200",0,,2025-03-09 00:00:00
35,36,abc,Laptop,electronics,abc,5,abc,15-03-2025
36,37,abc,Monitor,ELECTRONICS,abc,,abc,abc
37,38,abc,abc,abc,"1,200",abc,,abc
38,39,West,Mobile,electronics,abc,abc,abc,
39,40,South,abc,Electronics,abc,0,184.47,abc
40,41,North,Monitor,Accessories,1500$,4,-,15-03-2025
41,42,South,abc,abc,"1,200",three,abc,15-03-2025
42,43,East,abc,abc,"1,200",abc,abc,
43,44,abc,abc,abc,abc,4,abc,2025-01-13 00:00:00
44,45,North,Headphones,ELECTRONICS,1500$,0,289.57,2025-01-07 00:00:00
45,46,North,Laptop,electronics,1500$,abc,abc,2025-03-06 00:00:00
46,47,East,Laptop,ELECTRONICS,1500$,3,-,abc
47,48,East,Monitor,electronics,"1,200",,-,
48,49,abc,Headphones,ELECTRONICS,284,5,,2025/02/15
49,50,abc,Tablet,electronics,,0,,abc

In [14]:
df

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,NaN,Headphones,Accessories,"1,200",three,,2025/02/15
1,2,NaN,Laptop,Electronics,,three,,NaN
2,3,NaN,NaN,ELECTRONICS,NaN,,NaN,
3,4,NaN,NaN,ELECTRONICS,NaN,three,,2025-03-06 00:00:00
4,5,East,Tablet,Electronics,1500$,NaN,NaN,
5,6,NaN,Monitor,electronics,NaN,NaN,-,2025/02/15
6,7,East,Tablet,NaN,,NaN,-,
7,8,North,NaN,Accessories,1500$,NaN,70.22,
8,9,West,NaN,Electronics,"1,200",,109.44,2025-02-05 00:00:00
9,10,South,NaN,ELECTRONICS,NaN,0,NaN,15-03-2025
10,11,NaN,Laptop,Electronics,"1,200",three,NaN,NaN
11,12,West,Headphones,ELECTRONICS,"1,200",NaN,,
12,13,North,Headphones,electronics,NaN,NaN,NaN,15-03-2025
13,14,NaN,Laptop,electronics,,,NaN,
14,15,West,Laptop,Accessories,1783,1,,15-03-2025
15,16,North,Tablet,electronics,,,NaN,2025-02-17 00:00:00
16,17,North,NaN,ELECTRONICS,"1,200",,-,2025/02/15
17,18,NaN,Tablet,Electronics,,three,NaN,2025/02/15
18,19,NaN,Headphones,Accessories,"1,200",NaN,NaN,15-03-2025
19,20,NaN,NaN,ELECTRONICS,,three,,NaN
20,21,North,Mobile,Accessories,1007,three,,NaN
21,22,West,NaN,Electronics,NaN,NaN,NaN,2025-02-02 00:00:00
22,23,South,Monitor,Electronics,1487,,NaN,2025-03-18 00:00:00
23,24,NaN,NaN,NaN,1500$,,NaN,2025-01-08 00:00:00
24,25,West,Mobile,ELECTRONICS,,,-,2025-01-15 00:00:00
25,26,West,Mobile,Electronics,382,0,,
26,27,NaN,Laptop,electronics,"1,200",0,,
27,28,East,Monitor,ELECTRONICS,"1,200",NaN,459.39,
28,29,North,Headphones,NaN,NaN,0,214.92,
29,30,West,Monitor,Accessories,821,1,109.77,2025-01-12 00:00:00
30,31,NaN,Tablet,Electronics,237,,NaN,
31,32,NaN,Headphones,ELECTRONICS,1771,0,-,2025/02/15
32,33,NaN,Laptop,NaN,1500$,0,NaN,2025-02-20 00:00:00
33,34,South,Headphones,ELECTRONICS,NaN,4,107.67,
34,35,East,NaN,Accessories,"1,200",0,,2025-03-09 00:00:00
35,36,NaN,Laptop,electronics,NaN,5,NaN,15-03-2025
36,37,NaN,Monitor,ELECTRONICS,NaN,,NaN,NaN
37,38,NaN,NaN,NaN,"1,200",NaN,,NaN
38,39,West,Mobile,electronics,NaN,NaN,NaN,
39,40,South,NaN,Electronics,NaN,0,184.47,NaN
40,41,North,Monitor,Accessories,1500$,4,-,15-03-2025
41,42,South,NaN,NaN,"1,200",three,NaN,15-03-2025
42,43,East,NaN,NaN,"1,200",NaN,NaN,
43,44,NaN,NaN,NaN,NaN,4,NaN,2025-01-13 00:00:00
44,45,North,Headphones,ELECTRONICS,1500$,0,289.57,2025-01-07 00:00:00
45,46,North,Laptop,electronics,1500$,NaN,NaN,2025-03-06 00:00:00
46,47,East,Laptop,ELECTRONICS,1500$,3,-,NaN
47,48,East,Monitor,electronics,"1,200",,-,
48,49,NaN,Headphones,ELECTRONICS,284,5,,2025/02/15
49,50,NaN,Tablet,electronics,,0,,NaN

In [41]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [42]:
df['Date'].isnull().sum()

np.int64(0)

In [43]:
df['Date']

0    2025-02-15
1    2025-03-06
2    2025-03-06
3    2025-03-06
4    2025-02-15
5    2025-02-15
6    2025-02-05
7    2025-02-05
8    2025-02-05
9    2025-02-17
10   2025-02-17
11   2025-02-17
12   2025-02-17
13   2025-02-17
14   2025-02-17
15   2025-02-17
16   2025-02-15
17   2025-02-15
18   2025-02-02
19   2025-02-02
20   2025-02-02
21   2025-02-02
22   2025-03-18
23   2025-01-08
24   2025-01-15
25   2025-01-12
26   2025-01-12
27   2025-01-12
28   2025-01-12
29   2025-01-12
30   2025-02-15
31   2025-02-15
32   2025-02-20
33   2025-03-09
34   2025-03-09
35   2025-01-13
36   2025-01-13
37   2025-01-13
38   2025-01-13
39   2025-01-13
40   2025-01-13
41   2025-01-13
42   2025-01-13
43   2025-01-13
44   2025-01-07
45   2025-03-06
46   2025-02-15
47   2025-02-15
48   2025-02-15
49   2025-02-15
Name: Date, dtype: datetime64[ns]

In [44]:
df['Date'].bfill(inplace=True)

In [45]:
df['Date']

0    2025-02-15
1    2025-03-06
2    2025-03-06
3    2025-03-06
4    2025-02-15
5    2025-02-15
6    2025-02-05
7    2025-02-05
8    2025-02-05
9    2025-02-17
10   2025-02-17
11   2025-02-17
12   2025-02-17
13   2025-02-17
14   2025-02-17
15   2025-02-17
16   2025-02-15
17   2025-02-15
18   2025-02-02
19   2025-02-02
20   2025-02-02
21   2025-02-02
22   2025-03-18
23   2025-01-08
24   2025-01-15
25   2025-01-12
26   2025-01-12
27   2025-01-12
28   2025-01-12
29   2025-01-12
30   2025-02-15
31   2025-02-15
32   2025-02-20
33   2025-03-09
34   2025-03-09
35   2025-01-13
36   2025-01-13
37   2025-01-13
38   2025-01-13
39   2025-01-13
40   2025-01-13
41   2025-01-13
42   2025-01-13
43   2025-01-13
44   2025-01-07
45   2025-03-06
46   2025-02-15
47   2025-02-15
48   2025-02-15
49   2025-02-15
Name: Date, dtype: datetime64[ns]

In [46]:
df.isnull().sum()

Order_ID     0
Region      21
Product     15
Category     8
Sales        0
Quantity    13
Profit      21
Date         0
dtype: int64

In [47]:
df['Date'].ffill(inplace=True)

In [48]:
df.isnull().sum()

Order_ID     0
Region      21
Product     15
Category     8
Sales        0
Quantity    13
Profit      21
Date         0
dtype: int64

In [49]:
df['Region'] = df['Region'].str.strip()

In [50]:
df['Region']

0       NaN
1       NaN
2       NaN
3       NaN
4      East
5       NaN
6      East
7     North
8      West
9     South
10      NaN
11     West
12    North
13      NaN
14     West
15    North
16    North
17      NaN
18      NaN
19      NaN
20    North
21     West
22    South
23      NaN
24     West
25     West
26      NaN
27     East
28    North
29     West
30      NaN
31      NaN
32      NaN
33    South
34     East
35      NaN
36      NaN
37      NaN
38     West
39    South
40    North
41    South
42     East
43      NaN
44    North
45    North
46     East
47     East
48      NaN
49      NaN
Name: Region, dtype: object

In [51]:

df.replace("abc", np.nan, inplace=True)

In [31]:
df

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,NaN,Headphones,Accessories,"1,200",three,,2025-02-15
1,2,NaN,Laptop,Electronics,,three,,2025-03-06
2,3,NaN,NaN,ELECTRONICS,NaN,,NaN,2025-03-06
3,4,NaN,NaN,ELECTRONICS,NaN,three,,2025-03-06
4,5,East,Tablet,Electronics,1500$,NaN,NaN,2025-02-15
5,6,NaN,Monitor,electronics,NaN,NaN,-,2025-02-15
6,7,East,Tablet,NaN,,NaN,-,2025-02-05
7,8,North,NaN,Accessories,1500$,NaN,70.22,2025-02-05
8,9,West,NaN,Electronics,"1,200",,109.44,2025-02-05
9,10,South,NaN,ELECTRONICS,NaN,0,NaN,2025-02-17
10,11,NaN,Laptop,Electronics,"1,200",three,NaN,2025-02-17
11,12,West,Headphones,ELECTRONICS,"1,200",NaN,,2025-02-17
12,13,North,Headphones,electronics,NaN,NaN,NaN,2025-02-17
13,14,NaN,Laptop,electronics,,,NaN,2025-02-17
14,15,West,Laptop,Accessories,1783,1,,2025-02-17
15,16,North,Tablet,electronics,,,NaN,2025-02-17
16,17,North,NaN,ELECTRONICS,"1,200",,-,2025-02-15
17,18,NaN,Tablet,Electronics,,three,NaN,2025-02-15
18,19,NaN,Headphones,Accessories,"1,200",NaN,NaN,2025-02-02
19,20,NaN,NaN,ELECTRONICS,,three,,2025-02-02
20,21,North,Mobile,Accessories,1007,three,,2025-02-02
21,22,West,NaN,Electronics,NaN,NaN,NaN,2025-02-02
22,23,South,Monitor,Electronics,1487,,NaN,2025-03-18
23,24,NaN,NaN,NaN,1500$,,NaN,2025-01-08
24,25,West,Mobile,ELECTRONICS,,,-,2025-01-15
25,26,West,Mobile,Electronics,382,0,,2025-01-12
26,27,NaN,Laptop,electronics,"1,200",0,,2025-01-12
27,28,East,Monitor,ELECTRONICS,"1,200",NaN,459.39,2025-01-12
28,29,North,Headphones,NaN,NaN,0,214.92,2025-01-12
29,30,West,Monitor,Accessories,821,1,109.77,2025-01-12
30,31,NaN,Tablet,Electronics,237,,NaN,2025-02-15
31,32,NaN,Headphones,ELECTRONICS,1771,0,-,2025-02-15
32,33,NaN,Laptop,NaN,1500$,0,NaN,2025-02-20
33,34,South,Headphones,ELECTRONICS,NaN,4,107.67,2025-03-09
34,35,East,NaN,Accessories,"1,200",0,,2025-03-09
35,36,NaN,Laptop,electronics,NaN,5,NaN,2025-01-13
36,37,NaN,Monitor,ELECTRONICS,NaN,,NaN,2025-01-13
37,38,NaN,NaN,NaN,"1,200",NaN,,2025-01-13
38,39,West,Mobile,electronics,NaN,NaN,NaN,2025-01-13
39,40,South,NaN,Electronics,NaN,0,184.47,2025-01-13
40,41,North,Monitor,Accessories,1500$,4,-,2025-01-13
41,42,South,NaN,NaN,"1,200",three,NaN,2025-01-13
42,43,East,NaN,NaN,"1,200",NaN,NaN,2025-01-13
43,44,NaN,NaN,NaN,NaN,4,NaN,2025-01-13
44,45,North,Headphones,ELECTRONICS,1500$,0,289.57,2025-01-07
45,46,North,Laptop,electronics,1500$,NaN,NaN,2025-03-06
46,47,East,Laptop,ELECTRONICS,1500$,3,-,2025-02-15
47,48,East,Monitor,electronics,"1,200",,-,2025-02-15
48,49,NaN,Headphones,ELECTRONICS,284,5,,2025-02-15
49,50,NaN,Tablet,electronics,,0,,2025-02-15

In [52]:
df['Region'].fillna('East',inplace=True)

In [53]:
df['Region']

0      East
1      East
2      East
3      East
4      East
5      East
6      East
7     North
8      West
9     South
10     East
11     West
12    North
13     East
14     West
15    North
16    North
17     East
18     East
19     East
20    North
21     West
22    South
23     East
24     West
25     West
26     East
27     East
28    North
29     West
30     East
31     East
32     East
33    South
34     East
35     East
36     East
37     East
38     West
39    South
40    North
41    South
42     East
43     East
44    North
45    North
46     East
47     East
48     East
49     East
Name: Region, dtype: object

In [54]:
df.isnull().sum()

Order_ID     0
Region       0
Product     15
Category     8
Sales        0
Quantity    13
Profit      21
Date         0
dtype: int64

In [55]:
df['Product']

0     Headphones
1         Laptop
2            NaN
3            NaN
4         Tablet
5        Monitor
6         Tablet
7            NaN
8            NaN
9            NaN
10        Laptop
11    Headphones
12    Headphones
13        Laptop
14        Laptop
15        Tablet
16           NaN
17        Tablet
18    Headphones
19           NaN
20        Mobile
21           NaN
22       Monitor
23           NaN
24        Mobile
25        Mobile
26        Laptop
27       Monitor
28    Headphones
29       Monitor
30        Tablet
31    Headphones
32        Laptop
33    Headphones
34           NaN
35        Laptop
36       Monitor
37           NaN
38        Mobile
39           NaN
40       Monitor
41           NaN
42           NaN
43           NaN
44    Headphones
45        Laptop
46        Laptop
47       Monitor
48    Headphones
49        Tablet
Name: Product, dtype: object

In [56]:
df['Product'].fillna('Computer',inplace=True)

In [57]:
df['Product']

0     Headphones
1         Laptop
2       Computer
3       Computer
4         Tablet
5        Monitor
6         Tablet
7       Computer
8       Computer
9       Computer
10        Laptop
11    Headphones
12    Headphones
13        Laptop
14        Laptop
15        Tablet
16      Computer
17        Tablet
18    Headphones
19      Computer
20        Mobile
21      Computer
22       Monitor
23      Computer
24        Mobile
25        Mobile
26        Laptop
27       Monitor
28    Headphones
29       Monitor
30        Tablet
31    Headphones
32        Laptop
33    Headphones
34      Computer
35        Laptop
36       Monitor
37      Computer
38        Mobile
39      Computer
40       Monitor
41      Computer
42      Computer
43      Computer
44    Headphones
45        Laptop
46        Laptop
47       Monitor
48    Headphones
49        Tablet
Name: Product, dtype: object

In [58]:
df.isnull().sum()

Order_ID     0
Region       0
Product      0
Category     8
Sales        0
Quantity    13
Profit      21
Date         0
dtype: int64

In [59]:
df['Category'].fillna("Electronics",inplace=True)

In [60]:
df['Category'].str.upper()

0     ACCESSORIES
1     ELECTRONICS
2     ELECTRONICS
3     ELECTRONICS
4     ELECTRONICS
5     ELECTRONICS
6     ELECTRONICS
7     ACCESSORIES
8     ELECTRONICS
9     ELECTRONICS
10    ELECTRONICS
11    ELECTRONICS
12    ELECTRONICS
13    ELECTRONICS
14    ACCESSORIES
15    ELECTRONICS
16    ELECTRONICS
17    ELECTRONICS
18    ACCESSORIES
19    ELECTRONICS
20    ACCESSORIES
21    ELECTRONICS
22    ELECTRONICS
23    ELECTRONICS
24    ELECTRONICS
25    ELECTRONICS
26    ELECTRONICS
27    ELECTRONICS
28    ELECTRONICS
29    ACCESSORIES
30    ELECTRONICS
31    ELECTRONICS
32    ELECTRONICS
33    ELECTRONICS
34    ACCESSORIES
35    ELECTRONICS
36    ELECTRONICS
37    ELECTRONICS
38    ELECTRONICS
39    ELECTRONICS
40    ACCESSORIES
41    ELECTRONICS
42    ELECTRONICS
43    ELECTRONICS
44    ELECTRONICS
45    ELECTRONICS
46    ELECTRONICS
47    ELECTRONICS
48    ELECTRONICS
49    ELECTRONICS
Name: Category, dtype: object

In [61]:
df.isnull().sum()

Order_ID     0
Region       0
Product      0
Category     0
Sales        0
Quantity    13
Profit      21
Date         0
dtype: int64

In [28]:
df['Sales'] = df['Sales'].astype(str).str.replace(r'[$,]', '', regex=True)

In [29]:
df['Sales']

0     1200
1
2      nan
3      nan
4     1500
5      nan
6
7     1500
8     1200
9      nan
10    1200
11    1200
12     nan
13
14    1783
15
16    1200
17
18    1200
19
20    1007
21     nan
22    1487
23    1500
24
25     382
26    1200
27    1200
28     nan
29     821
30     237
31    1771
32    1500
33     nan
34    1200
35     nan
36     nan
37    1200
38     nan
39     nan
40    1500
41    1200
42    1200
43     nan
44    1500
45    1500
46    1500
47    1200
48     284
49
Name: Sales, dtype: object

In [30]:
df['Sales'].fillna(df['Sales'].min(),inplace=True)

In [31]:
df['Sales']

0     1200
1
2      nan
3      nan
4     1500
5      nan
6
7     1500
8     1200
9      nan
10    1200
11    1200
12     nan
13
14    1783
15
16    1200
17
18    1200
19
20    1007
21     nan
22    1487
23    1500
24
25     382
26    1200
27    1200
28     nan
29     821
30     237
31    1771
32    1500
33     nan
34    1200
35     nan
36     nan
37    1200
38     nan
39     nan
40    1500
41    1200
42    1200
43     nan
44    1500
45    1500
46    1500
47    1200
48     284
49
Name: Sales, dtype: object

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  50 non-null     int64
 1   Region    29 non-null     object
 2   Product   35 non-null     object
 3   Category  42 non-null     object
 4   Sales     50 non-null     object
 5   Quantity  37 non-null     object
 6   Profit    29 non-null     object
 7   Date      50 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 3.3+ KB

In [63]:
df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')

In [64]:
df['Sales'].fillna(df['Sales'].mean(), inplace=True)

In [35]:
df['Sales']

0     1200.000000
1     1219.724138
2     1219.724138
3     1219.724138
4     1500.000000
5     1219.724138
6     1219.724138
7     1500.000000
8     1200.000000
9     1219.724138
10    1200.000000
11    1200.000000
12    1219.724138
13    1219.724138
14    1783.000000
15    1219.724138
16    1200.000000
17    1219.724138
18    1200.000000
19    1219.724138
20    1007.000000
21    1219.724138
22    1487.000000
23    1500.000000
24    1219.724138
25     382.000000
26    1200.000000
27    1200.000000
28    1219.724138
29     821.000000
30     237.000000
31    1771.000000
32    1500.000000
33    1219.724138
34    1200.000000
35    1219.724138
36    1219.724138
37    1200.000000
38    1219.724138
39    1219.724138
40    1500.000000
41    1200.000000
42    1200.000000
43    1219.724138
44    1500.000000
45    1500.000000
46    1500.000000
47    1200.000000
48     284.000000
49    1219.724138
Name: Sales, dtype: float64

In [65]:
df['Sales'] = df['Sales'].round(0).astype(int)

In [66]:
df['Sales']

0     1200
1     1220
2     1220
3     1220
4     1500
5     1220
6     1220
7     1500
8     1200
9     1220
10    1200
11    1200
12    1220
13    1220
14    1783
15    1220
16    1200
17    1220
18    1200
19    1220
20    1007
21    1220
22    1487
23    1500
24    1220
25     382
26    1200
27    1200
28    1220
29     821
30     237
31    1771
32    1500
33    1220
34    1200
35    1220
36    1220
37    1200
38    1220
39    1220
40    1500
41    1200
42    1200
43    1220
44    1500
45    1500
46    1500
47    1200
48     284
49    1220
Name: Sales, dtype: int64

In [67]:
df.isnull().sum()

Order_ID     0
Region       0
Product      0
Category     0
Sales        0
Quantity    13
Profit      21
Date         0
dtype: int64

In [68]:
df['Quantity']

0     three
1     three
2
3     three
4       NaN
5       NaN
6       NaN
7       NaN
8
9         0
10    three
11      NaN
12      NaN
13
14        1
15
16
17    three
18      NaN
19    three
20    three
21      NaN
22
23
24
25        0
26        0
27      NaN
28        0
29        1
30
31        0
32        0
33        4
34        0
35        5
36
37      NaN
38      NaN
39        0
40        4
41    three
42      NaN
43        4
44        0
45      NaN
46        3
47
48        5
49        0
Name: Quantity, dtype: object

In [69]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  50 non-null     int64
 1   Region    50 non-null     object
 2   Product   50 non-null     object
 3   Category  50 non-null     object
 4   Sales     50 non-null     int64
 5   Quantity  18 non-null     float64
 6   Profit    29 non-null     object
 7   Date      50 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 3.3+ KB

In [75]:
df['Quantity']

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    1
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    1
30    0
31    0
32    0
33    4
34    0
35    5
36    0
37    0
38    0
39    0
40    4
41    0
42    0
43    4
44    0
45    0
46    3
47    0
48    5
49    0
Name: Quantity, dtype: int64

In [76]:
df['Quantity'] = np.random.randint(1, 11, size=len(df))

In [77]:
df['Quantity']

0      8
1      7
2     10
3      7
4      8
5     10
6      4
7      7
8     10
9      1
10     3
11     9
12     6
13     3
14     6
15     1
16     4
17    10
18     2
19     5
20     1
21     6
22     1
23     4
24     6
25     6
26     9
27     6
28     9
29    10
30     3
31     8
32     8
33     9
34     9
35     9
36     6
37     2
38     2
39     8
40     1
41     2
42     4
43     5
44     4
45     4
46     7
47     5
48     6
49     9
Name: Quantity, dtype: int32

In [78]:
df.isnull().sum()

Order_ID     0
Region       0
Product      0
Category     0
Sales        0
Quantity     0
Profit      21
Date         0
dtype: int64

In [79]:
df

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,East,Headphones,Accessories,1200,8,,2025-02-15
1,2,East,Laptop,Electronics,1220,7,,2025-03-06
2,3,East,Computer,ELECTRONICS,1220,10,NaN,2025-03-06
3,4,East,Computer,ELECTRONICS,1220,7,,2025-03-06
4,5,East,Tablet,Electronics,1500,8,NaN,2025-02-15
5,6,East,Monitor,electronics,1220,10,-,2025-02-15
6,7,East,Tablet,Electronics,1220,4,-,2025-02-05
7,8,North,Computer,Accessories,1500,7,70.22,2025-02-05
8,9,West,Computer,Electronics,1200,10,109.44,2025-02-05
9,10,South,Computer,ELECTRONICS,1220,1,NaN,2025-02-17
10,11,East,Laptop,Electronics,1200,3,NaN,2025-02-17
11,12,West,Headphones,ELECTRONICS,1200,9,,2025-02-17
12,13,North,Headphones,electronics,1220,6,NaN,2025-02-17
13,14,East,Laptop,electronics,1220,3,NaN,2025-02-17
14,15,West,Laptop,Accessories,1783,6,,2025-02-17
15,16,North,Tablet,electronics,1220,1,NaN,2025-02-17
16,17,North,Computer,ELECTRONICS,1200,4,-,2025-02-15
17,18,East,Tablet,Electronics,1220,10,NaN,2025-02-15
18,19,East,Headphones,Accessories,1200,2,NaN,2025-02-02
19,20,East,Computer,ELECTRONICS,1220,5,,2025-02-02
20,21,North,Mobile,Accessories,1007,1,,2025-02-02
21,22,West,Computer,Electronics,1220,6,NaN,2025-02-02
22,23,South,Monitor,Electronics,1487,1,NaN,2025-03-18
23,24,East,Computer,Electronics,1500,4,NaN,2025-01-08
24,25,West,Mobile,ELECTRONICS,1220,6,-,2025-01-15
25,26,West,Mobile,Electronics,382,6,,2025-01-12
26,27,East,Laptop,electronics,1200,9,,2025-01-12
27,28,East,Monitor,ELECTRONICS,1200,6,459.39,2025-01-12
28,29,North,Headphones,Electronics,1220,9,214.92,2025-01-12
29,30,West,Monitor,Accessories,821,10,109.77,2025-01-12
30,31,East,Tablet,Electronics,237,3,NaN,2025-02-15
31,32,East,Headphones,ELECTRONICS,1771,8,-,2025-02-15
32,33,East,Laptop,Electronics,1500,8,NaN,2025-02-20
33,34,South,Headphones,ELECTRONICS,1220,9,107.67,2025-03-09
34,35,East,Computer,Accessories,1200,9,,2025-03-09
35,36,East,Laptop,electronics,1220,9,NaN,2025-01-13
36,37,East,Monitor,ELECTRONICS,1220,6,NaN,2025-01-13
37,38,East,Computer,Electronics,1200,2,,2025-01-13
38,39,West,Mobile,electronics,1220,2,NaN,2025-01-13
39,40,South,Computer,Electronics,1220,8,184.47,2025-01-13
40,41,North,Monitor,Accessories,1500,1,-,2025-01-13
41,42,South,Computer,Electronics,1200,2,NaN,2025-01-13
42,43,East,Computer,Electronics,1200,4,NaN,2025-01-13
43,44,East,Computer,Electronics,1220,5,NaN,2025-01-13
44,45,North,Headphones,ELECTRONICS,1500,4,289.57,2025-01-07
45,46,North,Laptop,electronics,1500,4,NaN,2025-03-06
46,47,East,Laptop,ELECTRONICS,1500,7,-,2025-02-15
47,48,East,Monitor,electronics,1200,5,-,2025-02-15
48,49,East,Headphones,ELECTRONICS,284,6,,2025-02-15
49,50,East,Tablet,electronics,1220,9,,2025-02-15

In [80]:
df['Profit'] = pd.to_numeric(df['Profit'], errors='coerce')

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  50 non-null     int64
 1   Region    50 non-null     object
 2   Product   50 non-null     object
 3   Category  50 non-null     object
 4   Sales     50 non-null     int64
 5   Quantity  50 non-null     int32
 6   Profit    8 non-null      float64
 7   Date      50 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int32(1), int64(2), object(3)
memory usage: 3.1+ KB

In [83]:
df['Profit'] = df['Profit'].replace(['-', ''], np.nan)

In [84]:
df['Profit']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
6        NaN
7      70.22
8     109.44
9        NaN
10       NaN
11       NaN
12       NaN
13       NaN
14       NaN
15       NaN
16       NaN
17       NaN
18       NaN
19       NaN
20       NaN
21       NaN
22       NaN
23       NaN
24       NaN
25       NaN
26       NaN
27    459.39
28    214.92
29    109.77
30       NaN
31       NaN
32       NaN
33    107.67
34       NaN
35       NaN
36       NaN
37       NaN
38       NaN
39    184.47
40       NaN
41       NaN
42       NaN
43       NaN
44    289.57
45       NaN
46       NaN
47       NaN
48       NaN
49       NaN
Name: Profit, dtype: float64

In [86]:
df['Profit'] = df['Profit'].fillna(
    np.random.randint(50, 301, size=len(df))
)

TypeError: "value" parameter must be a scalar, dict or Series, but you passed a "ndarray"

In [88]:
df.loc[df['Profit'].isna(), 'Profit'] = np.random.randint(
    50, 100, 
    df['Profit'].isna().sum()
)

In [89]:
df['Profit']

0      96.00
1      56.00
2      76.00
3      78.00
4      57.00
5      69.00
6      70.00
7      70.22
8     109.44
9      80.00
10     85.00
11     82.00
12     54.00
13     53.00
14     58.00
15     64.00
16     60.00
17     90.00
18     79.00
19     97.00
20     62.00
21     93.00
22     74.00
23     80.00
24     91.00
25     94.00
26     99.00
27    459.39
28    214.92
29    109.77
30     88.00
31     82.00
32     51.00
33    107.67
34     58.00
35     76.00
36     59.00
37     86.00
38     87.00
39    184.47
40     98.00
41     66.00
42     60.00
43     67.00
44    289.57
45     73.00
46     85.00
47     95.00
48     97.00
49     71.00
Name: Profit, dtype: float64

In [92]:
df['Profit'] = df['Profit'].round(0)

In [93]:
df['Profit']

0      96.0
1      56.0
2      76.0
3      78.0
4      57.0
5      69.0
6      70.0
7      70.0
8     109.0
9      80.0
10     85.0
11     82.0
12     54.0
13     53.0
14     58.0
15     64.0
16     60.0
17     90.0
18     79.0
19     97.0
20     62.0
21     93.0
22     74.0
23     80.0
24     91.0
25     94.0
26     99.0
27    459.0
28    215.0
29    110.0
30     88.0
31     82.0
32     51.0
33    108.0
34     58.0
35     76.0
36     59.0
37     86.0
38     87.0
39    184.0
40     98.0
41     66.0
42     60.0
43     67.0
44    290.0
45     73.0
46     85.0
47     95.0
48     97.0
49     71.0
Name: Profit, dtype: float64

In [94]:
df.isnull().sum()

Order_ID    0
Region      0
Product     0
Category    0
Sales       0
Quantity    0
Profit      0
Date        0
dtype: int64

In [95]:
df

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,East,Headphones,Accessories,1200,8,96.0,2025-02-15
1,2,East,Laptop,Electronics,1220,7,56.0,2025-03-06
2,3,East,Computer,ELECTRONICS,1220,10,76.0,2025-03-06
3,4,East,Computer,ELECTRONICS,1220,7,78.0,2025-03-06
4,5,East,Tablet,Electronics,1500,8,57.0,2025-02-15
5,6,East,Monitor,electronics,1220,10,69.0,2025-02-15
6,7,East,Tablet,Electronics,1220,4,70.0,2025-02-05
7,8,North,Computer,Accessories,1500,7,70.0,2025-02-05
8,9,West,Computer,Electronics,1200,10,109.0,2025-02-05
9,10,South,Computer,ELECTRONICS,1220,1,80.0,2025-02-17
10,11,East,Laptop,Electronics,1200,3,85.0,2025-02-17
11,12,West,Headphones,ELECTRONICS,1200,9,82.0,2025-02-17
12,13,North,Headphones,electronics,1220,6,54.0,2025-02-17
13,14,East,Laptop,electronics,1220,3,53.0,2025-02-17
14,15,West,Laptop,Accessories,1783,6,58.0,2025-02-17
15,16,North,Tablet,electronics,1220,1,64.0,2025-02-17
16,17,North,Computer,ELECTRONICS,1200,4,60.0,2025-02-15
17,18,East,Tablet,Electronics,1220,10,90.0,2025-02-15
18,19,East,Headphones,Accessories,1200,2,79.0,2025-02-02
19,20,East,Computer,ELECTRONICS,1220,5,97.0,2025-02-02
20,21,North,Mobile,Accessories,1007,1,62.0,2025-02-02
21,22,West,Computer,Electronics,1220,6,93.0,2025-02-02
22,23,South,Monitor,Electronics,1487,1,74.0,2025-03-18
23,24,East,Computer,Electronics,1500,4,80.0,2025-01-08
24,25,West,Mobile,ELECTRONICS,1220,6,91.0,2025-01-15
25,26,West,Mobile,Electronics,382,6,94.0,2025-01-12
26,27,East,Laptop,electronics,1200,9,99.0,2025-01-12
27,28,East,Monitor,ELECTRONICS,1200,6,459.0,2025-01-12
28,29,North,Headphones,Electronics,1220,9,215.0,2025-01-12
29,30,West,Monitor,Accessories,821,10,110.0,2025-01-12
30,31,East,Tablet,Electronics,237,3,88.0,2025-02-15
31,32,East,Headphones,ELECTRONICS,1771,8,82.0,2025-02-15
32,33,East,Laptop,Electronics,1500,8,51.0,2025-02-20
33,34,South,Headphones,ELECTRONICS,1220,9,108.0,2025-03-09
34,35,East,Computer,Accessories,1200,9,58.0,2025-03-09
35,36,East,Laptop,electronics,1220,9,76.0,2025-01-13
36,37,East,Monitor,ELECTRONICS,1220,6,59.0,2025-01-13
37,38,East,Computer,Electronics,1200,2,86.0,2025-01-13
38,39,West,Mobile,electronics,1220,2,87.0,2025-01-13
39,40,South,Computer,Electronics,1220,8,184.0,2025-01-13
40,41,North,Monitor,Accessories,1500,1,98.0,2025-01-13
41,42,South,Computer,Electronics,1200,2,66.0,2025-01-13
42,43,East,Computer,Electronics,1200,4,60.0,2025-01-13
43,44,East,Computer,Electronics,1220,5,67.0,2025-01-13
44,45,North,Headphones,ELECTRONICS,1500,4,290.0,2025-01-07
45,46,North,Laptop,electronics,1500,4,73.0,2025-03-06
46,47,East,Laptop,ELECTRONICS,1500,7,85.0,2025-02-15
47,48,East,Monitor,electronics,1200,5,95.0,2025-02-15
48,49,East,Headphones,ELECTRONICS,284,6,97.0,2025-02-15
49,50,East,Tablet,electronics,1220,9,71.0,2025-02-15