In [ ]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_excel(r"D:\UV DA\UV python\Sales_Project_Data.xlsx")

In [5]:
df

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,East,Mobile,Electronics,990,5,160.68,2025-04-10
1,2,North,Laptop,Electronics,1413,4,381.51,2025-03-25
2,3,West,Laptop,Electronics,1519,2,341.82,2025-03-19
3,4,North,Headphones,Accessories,1689,4,476.28,2025-05-14
4,5,East,Laptop,Electronics,790,1,88.48,2025-04-02
...,...,...,...,...,...,...,...,...
195,196,South,Tablet,Electronics,290,5,83.13,2025-04-24
196,197,West,Headphones,Accessories,303,4,75.10,2025-01-01
197,198,North,Mobile,Electronics,1591,2,358.29,2025-03-04
198,199,South,Monitor,Electronics,1817,1,390.65,2025-06-27
199,200,East,Mobile,Electronics,1061,5,207.12,2025-02-27

In [6]:
df.head()

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
0,1,East,Mobile,Electronics,990,5,160.68,2025-04-10
1,2,North,Laptop,Electronics,1413,4,381.51,2025-03-25
2,3,West,Laptop,Electronics,1519,2,341.82,2025-03-19
3,4,North,Headphones,Accessories,1689,4,476.28,2025-05-14
4,5,East,Laptop,Electronics,790,1,88.48,2025-04-02

In [8]:
df.tail()

,Order_ID,Region,Product,Category,Sales,Quantity,Profit,Date
195,196,South,Tablet,Electronics,290,5,83.13,2025-04-24
196,197,West,Headphones,Accessories,303,4,75.10,2025-01-01
197,198,North,Mobile,Electronics,1591,2,358.29,2025-03-04
198,199,South,Monitor,Electronics,1817,1,390.65,2025-06-27
199,200,East,Mobile,Electronics,1061,5,207.12,2025-02-27

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  200 non-null    int64
 1   Region    200 non-null    object
 2   Product   200 non-null    object
 3   Category  200 non-null    object
 4   Sales     200 non-null    int64
 5   Quantity  200 non-null    int64
 6   Profit    200 non-null    float64
 7   Date      200 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), object(3)
memory usage: 12.6+ KB

In [11]:
df.shape

(200, 8)

In [12]:
df.columns

Index(['Order_ID', 'Region', 'Product', 'Category', 'Sales', 'Quantity',
       'Profit', 'Date'],
      dtype='object')

In [13]:
df['Profit'].sum()

np.float64(45561.42)

In [14]:
df.describe()

         Order_ID        Sales    Quantity      Profit                 Date
count  200.000000   200.000000  200.000000  200.000000                  200
mean   100.500000  1110.935000    3.120000  227.807100  2025-04-04 09:36:00
min      1.000000   216.000000    1.000000   36.710000  2025-01-01 00:00:00
25%     50.750000   701.750000    2.000000  133.702500  2025-02-20 12:00:00
50%    100.500000  1125.000000    3.000000  206.535000  2025-04-08 00:00:00
75%    150.250000  1530.250000    4.000000  314.620000  2025-05-20 06:00:00
max    200.000000  1996.000000    5.000000  560.870000  2025-06-30 00:00:00
std     57.879185   496.288173    1.426807  124.001577                  NaN

In [16]:
df[['Profit','Sales']].describe

<bound method NDFrame.describe of      Profit  Sales
0    160.68    990
1    381.51   1413
2    341.82   1519
3    476.28   1689
4     88.48    790
..      ...    ...
195   83.13    290
196   75.10    303
197  358.29   1591
198  390.65   1817
199  207.12   1061

[200 rows x 2 columns]>

In [17]:
df.isnull()

     Order_ID  Region  Product  Category  Sales  Quantity  Profit   Date
0       False   False    False     False  False     False   False  False
1       False   False    False     False  False     False   False  False
2       False   False    False     False  False     False   False  False
3       False   False    False     False  False     False   False  False
4       False   False    False     False  False     False   False  False
..        ...     ...      ...       ...    ...       ...     ...    ...
195     False   False    False     False  False     False   False  False
196     False   False    False     False  False     False   False  False
197     False   False    False     False  False     False   False  False
198     False   False    False     False  False     False   False  False
199     False   False    False     False  False     False   False  False

[200 rows x 8 columns]

In [19]:
df.isnull().sum()

Order_ID    0
Region      0
Product     0
Category    0
Sales       0
Quantity    0
Profit      0
Date        0
dtype: int64

In [22]:
df.rename(columns={"Region":"Area"},inplace=True)

In [23]:
df

,Order_ID,Area,Product,Category,Sales,Quantity,Profit,Date
0,1,East,Mobile,Electronics,990,5,160.68,2025-04-10
1,2,North,Laptop,Electronics,1413,4,381.51,2025-03-25
2,3,West,Laptop,Electronics,1519,2,341.82,2025-03-19
3,4,North,Headphones,Accessories,1689,4,476.28,2025-05-14
4,5,East,Laptop,Electronics,790,1,88.48,2025-04-02
...,...,...,...,...,...,...,...,...
195,196,South,Tablet,Electronics,290,5,83.13,2025-04-24
196,197,West,Headphones,Accessories,303,4,75.10,2025-01-01
197,198,North,Mobile,Electronics,1591,2,358.29,2025-03-04
198,199,South,Monitor,Electronics,1817,1,390.65,2025-06-27
199,200,East,Mobile,Electronics,1061,5,207.12,2025-02-27

In [24]:
df.iloc[2:50,3:7]

       Category  Sales  Quantity  Profit
2   Electronics   1519         2  341.82
3   Accessories   1689         4  476.28
4   Electronics    790         1   88.48
5   Electronics    528         1   57.72
6   Electronics    790         5  136.22
7   Electronics   1665         5  465.41
8   Accessories    683         4   93.44
9   Electronics   1307         3  348.16
10  Electronics    219         2   64.57
11  Electronics   1897         2  429.76
12  Electronics   1755         5  501.15
13  Electronics   1520         1  410.45
14  Electronics    726         5  138.63
15  Electronics   1337         3  329.36
16  Accessories   1120         2  132.83
17  Electronics    733         4  140.76
18  Electronics   1123         3  252.75
19  Accessories   1092         2  180.80
20  Accessories    460         5   58.90
21  Electronics    666         3  144.40
22  Electronics    920         5  190.17
23  Electronics   1930         4  241.03
24  Electronics   1732         3  192.49
25  Electronics    928         5  122.06
26  Electronics    951         2  136.05
27  Electronics    674         1  146.70
28  Electronics    767         5  103.65
29  Electronics   1062         5  226.91
30  Electronics    999         5  215.28
31  Accessories   1204         5  234.83
32  Electronics    749         5  150.88
33  Electronics    714         2  127.79
34  Electronics    944         1  154.84
35  Electronics   1982         5  277.58
36  Electronics    474         5   74.28
37  Accessories   1823         3  225.63
38  Electronics   1155         2  335.03
39  Accessories   1625         5  252.47
40  Electronics   1530         4  313.52
41  Electronics    286         5   82.26
42  Electronics    640         3  156.71
43  Electronics   1058         3  225.63
44  Electronics   1580         2  403.89
45  Electronics    781         4  229.85
46  Accessories    567         2  143.64
47  Electronics    814         3  211.56
48  Electronics    900         4  132.23
49  Electronics    990         2  171.58

In [25]:
df.loc[0:40,'Product':'Profit']

       Product     Category  Sales  Quantity  Profit
0       Mobile  Electronics    990         5  160.68
1       Laptop  Electronics   1413         4  381.51
2       Laptop  Electronics   1519         2  341.82
3   Headphones  Accessories   1689         4  476.28
4       Laptop  Electronics    790         1   88.48
5       Tablet  Electronics    528         1   57.72
6       Tablet  Electronics    790         5  136.22
7       Laptop  Electronics   1665         5  465.41
8   Headphones  Accessories    683         4   93.44
9       Laptop  Electronics   1307         3  348.16
10      Laptop  Electronics    219         2   64.57
11      Mobile  Electronics   1897         2  429.76
12      Mobile  Electronics   1755         5  501.15
13      Mobile  Electronics   1520         1  410.45
14      Laptop  Electronics    726         5  138.63
15     Monitor  Electronics   1337         3  329.36
16  Headphones  Accessories   1120         2  132.83
17      Tablet  Electronics    733         4  140.76
18      Tablet  Electronics   1123         3  252.75
19  Headphones  Accessories   1092         2  180.80
20  Headphones  Accessories    460         5   58.90
21     Monitor  Electronics    666         3  144.40
22      Mobile  Electronics    920         5  190.17
23     Monitor  Electronics   1930         4  241.03
24      Mobile  Electronics   1732         3  192.49
25      Laptop  Electronics    928         5  122.06
26     Monitor  Electronics    951         2  136.05
27     Monitor  Electronics    674         1  146.70
28      Mobile  Electronics    767         5  103.65
29      Laptop  Electronics   1062         5  226.91
30      Tablet  Electronics    999         5  215.28
31  Headphones  Accessories   1204         5  234.83
32      Tablet  Electronics    749         5  150.88
33      Mobile  Electronics    714         2  127.79
34     Monitor  Electronics    944         1  154.84
35      Tablet  Electronics   1982         5  277.58
36      Mobile  Electronics    474         5   74.28
37  Headphones  Accessories   1823         3  225.63
38      Tablet  Electronics   1155         2  335.03
39  Headphones  Accessories   1625         5  252.47
40      Mobile  Electronics   1530         4  313.52

In [26]:
df['Quantity'] = df['Quantity'].astype(int)

In [27]:
df

,Order_ID,Area,Product,Category,Sales,Quantity,Profit,Date
0,1,East,Mobile,Electronics,990,5,160.68,2025-04-10
1,2,North,Laptop,Electronics,1413,4,381.51,2025-03-25
2,3,West,Laptop,Electronics,1519,2,341.82,2025-03-19
3,4,North,Headphones,Accessories,1689,4,476.28,2025-05-14
4,5,East,Laptop,Electronics,790,1,88.48,2025-04-02
...,...,...,...,...,...,...,...,...
195,196,South,Tablet,Electronics,290,5,83.13,2025-04-24
196,197,West,Headphones,Accessories,303,4,75.10,2025-01-01
197,198,North,Mobile,Electronics,1591,2,358.29,2025-03-04
198,199,South,Monitor,Electronics,1817,1,390.65,2025-06-27
199,200,East,Mobile,Electronics,1061,5,207.12,2025-02-27

In [30]:
df['Area'].value_counts()

Area
West     54
North    51
East     49
South    46
Name: count, dtype: int64

In [31]:
df['Category'].value_counts()

Category
Electronics    166
Accessories     34
Name: count, dtype: int64

In [33]:
pd.pivot_table(df,
               values='Sales',
               index='Area',
               columns='Category',
               aggfunc='sum')

Category  Accessories  Electronics
Area
East             8397        48750
North           11856        48470
South           15031        35389
West             7211        47083

In [34]:
df.nlargest(5, 'Sales')

,Order_ID,Area,Product,Category,Sales,Quantity,Profit,Date
110,111,North,Monitor,Electronics,1996,2,512.83,2025-05-30
127,128,East,Headphones,Accessories,1987,5,292.27,2025-05-25
35,36,West,Tablet,Electronics,1982,5,277.58,2025-05-14
69,70,West,Mobile,Electronics,1977,4,503.25,2025-04-05
166,167,North,Monitor,Electronics,1943,4,540.90,2025-04-24

In [35]:
df.nsmallest(5, 'Profit')

     Order_ID   Area  Product     Category  Sales  Quantity  Profit       Date
169       170  North  Monitor  Electronics    216         3   36.71 2025-06-10
162       163  North  Monitor  Electronics    232         4   39.90 2025-04-12
98         99  North   Laptop  Electronics    302         2   48.24 2025-02-12
143       144   East  Monitor  Electronics    385         3   48.25 2025-05-18
50         51   West   Mobile  Electronics    482         3   50.16 2025-05-23